import { v4 as uuidv4 } from 'uuid';

const tagsArray = ["All",
                   "UI",
                   "UX",
                   "Enhancement",
                   "Bug",
                   "Feature"];
const postArray = [{key: "a", rating: 112, header: "Add tags for solutions", description: "Easier to search for solutions based on a specific stack", tags:tagsArray[3], comments: [{key: uuidv4(), name: "Elijah Moss", nickname:"@hexagon.bestagon", text: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.", reply:[]},
                                                                                                                                                                                    {key: uuidv4(), name: "James Skinner", nickname:"@hummingbird", text: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
                                                                                                                                                                                     reply: [{key: uuidv4(), name:"Anne Valentive", nickname:"@annev1990", text:" If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. ", to:"@hummingbird"},
                                                                                                                                                                                             {key: uuidv4(), name:"Ryan Welles", nickname:"@voyager.344", text:" It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable.", to:"@annev1990"}
                                                                                                                                                                                    ]}
                                                                                                                                                                                   ]},
                   {key: "b", rating: 99, header: "Add a dark theme option", description: "It would help people with light sensitivies and who prefer dark mode", tags: tagsArray[5], comments: [{name: "name", nickname:"@nickname", text: "There are many variations of passages of Lorem Ipsum available",  reply:[], key: uuidv4() },{name: "name", nickname:"@nickname", text: "There are many variations of passages of Lorem Ipsum available",reply:[], key: uuidv4()},{name: "name", nickname:"@nickname", text: "There are many variations of passages of Lorem Ipsum available", reply:[], key: uuidv4()}]},
                   {key: "c", rating: 6, header: "Q&A within the challenge hubs", description: "Challenge-specific Q&A would make for easy reference", tags: tagsArray[5], comments: [{name: "name", nickname:"@nickname", text: "There are many variations of passages of Lorem Ipsum available",  reply:[], key: uuidv4() }]},
                   {key: "d", rating: 51, header: "Allow image/video upload to feedback", description: "Images and screencasts enchance comments on solutions", tags: tagsArray[3], comments: [{name: "name", nickname:"@nickname", text: "There are many variations of passages of Lorem Ipsum available",  reply:[], key: uuidv4() },{name: "name", nickname:"@nickname", text: "There are many variations of passages of Lorem Ipsum available",  reply:[], key: uuidv4() }]},
                   {key: "e", rating: 42, header: "Ability to follow others", description: "Stay updated on comments and solutions other people post", tags: tagsArray[5], comments: [{name: "name", nickname:"@nickname", text: "There are many variations of passages of Lorem Ipsum available",  reply:[], key: uuidv4() },{name: "name", nickname:"@nickname", text: "There are many variations of passages of Lorem Ipsum available",  reply:[], key: uuidv4() },{name: "name", nickname:"@nickname", text: "There are many variations of passages of Lorem Ipsum available",  reply:[], key: uuidv4() }]},
                   {key: "f", rating: 30, header: "Preview images lot loading", description: "Challenge preview images are missing when you apply a filter", tags: tagsArray[4], comments: []}];
//,jsnickname:"@nickname", text: "There are many variations of passages of Lorem Ipsum available",
export  {postArray, tagsArray};                   